### PR TITLE
new: Adding redis as a top-level dependency.

### PR DESCRIPTION
**Pull request by cschreep**
Roger and Dug both need to talk to the same redis instance. This change
makes that possible.

### CODE REVIEW

**Comment by YaphetKG** [comment]
Hi @cschreep , is there a reason to include bitnami redis in charts unzipped, as opposed to adding a dependency ref in the parent chart.yaml ?

**Comment by cschreep** [comment]
@YaphetKG nope, that shouldn't have been in the commit, removing

**Comment by pj-linebaugh** [comment]
Can you update the 'version' value (I believe this would be a minor/patch version update) in both charts and the parent helx chart?  I've been using [helm-docs](https://github.com/norwoodj/helm-docs) to autogenerate the README.md files for the charts, so would be good to run and commit the updated README.md files.  For the chart tarball packages, I'm wondering if we should limit those to being added into a certain branch, like gh-pages, which is what is being used for the Helm chart repository.  Maybe we should think about having the Helm package repository separate from the git repo so we don't have to add them at all.

**Comment by cschreep** [comment]
@pj-linebaugh sorry it took so long to get back to this. 

I'll update the versions for this PR, but it doesn't quite seems like a good strategy. Version numbers reflect releases, not developmental stages, so they should be done only when develop gets merged into master or otherwise released. 

Because we have multiple applications written as one big chart, the versioning strategy becomes even murkier. We should keep this in mind as we think of potential new designs or structures for maintaining all our helm charts

**Comment by pj-linebaugh** [comment]
Guess I've been a bit aggressive on my versioning.  I'll work on that.  There's also a few different types of versions in play.  The chart version and appVersion, and also the image version.  Another version would be the release version on github.  Anyways, should have a conversion soon about all this.

**Comment by YaphetKG** [comment]
> Guess I've been a bit aggressive on my versioning. I'll work on that. There's also a few different types of versions in play. The chart version and appVersion, and also the image version. Another version would be the release version on github. Anyways, should have a conversion soon about all this.

Just some ideas/questions, if a set of versioned images do not affect the structure of the chart maybe we can just update the app version of the chart. If it requires restructuring of the deployments maybe Chart version changes there (?)

**Comment by YaphetKG** [comment]
@cschreep , Do we want to manage `redis-secret` creation as part of this chart ?

**Comment by cschreep** [comment]
My rule of thumb is 1 application = 1 repo = 1 versioned thing = 1 CI/CD pipeline

So if a helm chart has a version number, that means it gets its own repo. In this strategy, the helx chart then gets its own dedicated repo and includes the other apps and versions in its dependencies list. When we bump those dependencies, we bump the version number (in the same way when you have a python app and update the dependencies in the requirements.txt). Likewise, Jenkins is watching each git repo to automatically build & publish when we release a new version. Because we have a large number of applications and want uniform behavior for all the chart repos, it might be beneficial to create a dedicated organization, helx-charts or something similar, to group all these repos under. 

This also means that the chart is version controlled in a separate repo from its application, e.g. there is a roger repo that defines the application, and a roger-chart repo that defines the chart. 

In the case of roger and dug, the charts need to be robust enough to support standalone deployment (bringing all the backend services with them) or integrated deployment (passing existing backend services into them).

This means more repos, but repositories are cheap and IMHO it's easier to maintain a simple CI/CD strategy that applies uniformly to many small repos than it is to maintain one complex CI/CD strategy that applies to one huge repo

**Comment by pj-linebaugh** [comment]
> > Guess I've been a bit aggressive on my versioning. I'll work on that. There's also a few different types of versions in play. The chart version and appVersion, and also the image version. Another version would be the release version on github. Anyways, should have a conversion soon about all this.
> 
> Just some ideas/questions, if a set of versioned images do not affect the structure of the chart maybe we can just update the app version of the chart. If it requires restructuring of the deployments maybe Chart version changes there (?)

What I've been doing (and suggested in the chart templates) is to update the chart version if the chart code (including appVersion/image version) is updated.  If the image is updated then update the appVersion, so appVersion is the same as the image version.  If a subchart version is updated then I increase the parent chart version.

**Comment by pj-linebaugh** [comment]
I think this is good to merge.  If there's something wrong, we'll fix.

**Review by YaphetKG — APPROVED** [review]

**Pull request merged**
