### PR TITLE
Added some updates

### PR DESCRIPTION
**Pull request by waTeim**
Some updates.

* Avoid a lot of apt-get stuff
* Get node.js via layers
* more via pip
* default python to 3.9 (as `python`)
* updated docker install per docs from docker.io

### CODE REVIEW

**Review by cnbennett3 — COMMENTED** [review]
Hi Jeff, please consider the following comments:
- Move lines 18-19 above line 14 and remove line 20 so the apt-update only has to be done once.
- Combine RUN lines 21-30 into a single RUN line by using "&& \\" at the end of each line to
reduce the number of layers created by the Dockerfile.
- Remove lines 51-56 since clair is no longer used.
Thanks--
Chuck

**Comment by waTeim** [comment]
Updated.  I did use the `&&` syntax to reduce layers and also remove clair, but I needed to keep 2 apt-get updates, 1 to get the most up-to date certs, curl, etc, and 2nd to get the new source code after inclusion of the new (docker) repo

**Comment by mac-chaffee** [comment]
Layers look good, I had 2 more comments here: https://github.com/helxplatform/devops/pull/165

**Comment by waTeim** [comment]
pinned node layer to node:16
pinned pip packages
* pytest to 7.1.x
* docker to 5.0.x
* pyyaml to 6.0.x
* jinja2 to 3.1.x

**Review by mac-chaffee — APPROVED** [review]
Remember to rebuild and push to containers.renci.org with these instructions https://wiki.renci.org/index.php?title=Containers.renci.org and the Makefile. I just granted access to you, Chuck, and Tyler

**Pull request merged**
