### PR TITLE
Making airflow auth optional

### PR DESCRIPTION
**Pull request by cschreep**

### CODE REVIEW

**Review by YaphetKG — APPROVED** [review]
lgtm

**Review by pj-linebaugh — CHANGES_REQUESTED** [review]
I think you also need to change the nginx dependency version in helx/Chart.yaml.

**Comment by cschreep** [comment]
@pj-linebaugh updated

**Review by pj-linebaugh — APPROVED** [review]
No doc updates, but I'll let it pass.

**Pull request merged**
