### PR TITLE
Roger helm

### PR DESCRIPTION
**Pull request by YaphetKG**
Enables automatically setting env vars for worker pods

### CODE REVIEW

**Review by pj-linebaugh — CHANGES_REQUESTED** [review]
Can you also update the chart 'version' in Chart.yaml?  When changes are made to the chart that should be updated.  The 'version' in helx/Chart.yaml should be incremented along with that.

**Comment by YaphetKG** [comment]
> Can you also update the chart 'version' in Chart.yaml? When changes are made to the chart that should be updated. The 'version' in helx/Chart.yaml should be incremented along with that.

hi @pj-linebaugh  chart version is incremented to 0.1.4

**Review by pj-linebaugh — CHANGES_REQUESTED** [review]
Can you update the helx parent chart 'version' too?

**Comment by YaphetKG** [comment]
> Can you update the helx parent chart 'version' too?

Done

**Pull request merged**
