### PR TITLE
Fix/redis pvc

### PR DESCRIPTION
**Pull request by cschreep**
Updates for search chart to handle inconsistent behavior setting up the redis PVC

### CODE REVIEW

**Review by pj-linebaugh — COMMENTED** [review]
Looks good, but can you also update the version and appVersion in the Chart.yaml, the helx/Chart.yaml version and search dependency, and the readme docs?

**Comment by cschreep** [comment]
Bumped the versions, didn't see a script to update the README?

**Review by YaphetKG — APPROVED** [review]
LGTM

**Comment by YaphetKG** [comment]
> Bumped the versions, didn't see a script to update the README?

I usually use this helm-docs container when doing those updates
```

docker run --rm --volume "$(pwd):/helm-docs"  jnorwood/helm-docs:latest 
```
https://github.com/norwoodj/helm-docs

**Comment by pj-linebaugh** [comment]
helm-docs, as Yaphete stated, is what is used to update/create the readme files.  Run it with your CWD as devops/helx.

**Comment by cschreep** [comment]
Something is funky with this and the other ambassador changes @pj-linebaugh merged in. I'm going to make a clean PR to make sure it's all sorted out

**Pull request closed without merging**
